### ISSUE TITLE
using moment.js / changing date format

### ISSUE THREAD

**Issue by m3l7** [emn178/angular2-chartjs#12]
hello,
I need to change the date label localizaton when using a datetime axis.

I've read in the chart.js docs that I need to change moment.js settings, which is included in the bundled version of chart.js.

Is there a way to access the moment.js object?

**Comment by emn178** [comment]
use moment TypeScript definitions
```
npm install --save @types/moment
```
and in your code
```TypeScript
import * as moment from 'moment';
```

**Comment by m3l7** [comment]
that worked.

thank you very much!
