### ISSUE TITLE
how to hide the legends and the tooltip of a pie chart?

### ISSUE THREAD

**Issue by sanuradhag** [emn178/angular2-chartjs#14]
`<chart [type]="'pie'" [data]="pieChartData" [options]="pieChartOptions"></chart>`

`this.pieChartData = {
      labels: [],
      datasets: [
        {
          data: [successCount, failedCount, pendingCount]
        }
      ]
    }`

    `this.pieChartOptions = {
      tooltips: {
        enabled: false
      }
    }`

This does not work.. It hides the legends, But tooltip displays undefined. I want to disable the tooltip,

**Comment by emn178** [comment]
```
  tooltips: {
    enabled: false
  }
```

**Comment by sanuradhag** [comment]
I'm sorry it was 
   `tooltips: {
    enabled: false
  }`

but it didn't work
