### ISSUE TITLE
update content on angular2

### ISSUE THREAD

**Issue by yadbo** [emn178/angular2-chartjs#18]
Hello there, is there a way for dynamically updating data for angular2?
I checked it out: even when my model is changed, chart stays the same.

**Comment by emn178** [comment]
Hi, it will redraw if data reference changed.
```HTML
<chart [type]="type" [data]="data" [options]="options"></chart>
```
in compenent
```TypeScript
this.data = { ... }; // new reference
```
If you change the property of the same instance, you have to call update() method.
```TypeScript
this.data.datasets = ... // modify properties

// call update() manully
this.chartComponent.chart.update();
```

**Comment by yadbo** [comment]
Thank you for responding. I thought updating a value would be enough but it wasn't. I copied data as tmp variable and re-set the data again. So it worked.
