### ISSUE TITLE
update the chart type (line/bar) dynamically

### ISSUE THREAD

**Issue by gbourda** [emn178/angular2-chartjs#23]
Hello,

Thanks for this awesome lib! 

I would like to switch dynamically between two different chart type: 'bar' and 'line'... 
Is it possible? 

Perhaps using this.chart.chart.update() ? 

Thanks for your time!

**Comment by emn178** [comment]
It can't support this currently. I will add this feature later.

**Comment by emn178** [comment]
add this feature into v0.3.0 . Please try it.
