### ISSUE TITLE
Can't get the stacked bar chart to display

### ISSUE THREAD

**Issue by anavgale** [emn178/angular2-chartjs#25]
Hi,

I updated the given sample to display stacked bar like this -

  type = 'bar';

  data = {
    labels: ["January", "February", "March", "April", "May", "June", "July"],
    datasets: [
      {
        label: "My First dataset",
        data: [65, 59, 80, 81, 56, 55, 40]
      },
      {
        label: "My Second dataset",
        data: [60, 65, 75, 86, 49, 42, 35]
      },
      {
        label: "My Third dataset",
        data: [35, 59, 50, 61, 76, 46, 35]
      },
    ]
  };
  
  options: {
    scales: {
        xAxes: [{
            stacked: true
        }],
        yAxes: [{
            stacked: true
        }]
    }
}

but it still does not show the stacked bar. Instead it shows three bars next to each other. 

How can I get the stacked bar?

**Comment by emn178** [comment]
you need to set color for recognition
```JavaScript
data = {
  labels: ["January", "February", "March", "April", "May", "June", "July"],
  datasets: [
    {
      label: "My First dataset",
      data: [65, 59, 80, 81, 56, 55, 40],
      backgroundColor: '#FF6384'
    },
    {
      label: "My Second dataset",
      data: [60, 65, 75, 86, 49, 42, 35],
      backgroundColor: '#36A2EB'
    },
    {
      label: "My Third dataset",
      data: [35, 59, 50, 61, 76, 46, 35],
      backgroundColor: '#FFCE56'
    },
  ]
};
```

**Comment by mohitook** [comment]
unfortunately it doesn't work even in this way:
![image](https://user-images.githubusercontent.com/15103326/31626344-a2f8fe84-b2a9-11e7-90b4-095598e8b96d.png)

**Comment by emn178** [comment]
Did you set stacked?
```JavaScript
options = {
  scales: {
    xAxes: [
      {
        stacked: true
      }
    ],
    yAxes: [
      {
        stacked: true
      }
    ]
  }
};
```

**Comment by mohitook** [comment]
@emn178  yes of course! + info horizontalBar doesn't work as well!

**Comment by emn178** [comment]
I created a sample.
https://emn178.github.io/angular2-chartjs-sample/demo/

It can work.
