### ISSUE TITLE
`Responsive` seems to be broken when used with chart.js >= 2.7.0

### ISSUE THREAD

**Issue by jasonburrows** [emn178/angular2-chartjs#26]
In version 2.6.x of `chart.js`, combined with `angular2-chartjs` v0.3.0 I could create a doughnut chart that would fill its container like this:  (note the 300px wide div is just an example of a container with a width that I'd expect the chart to fill 90% of).

```
    <div style="width:100%; max-width:300px;">
        <chart style=" min-width:0;  max-width: 90%;"  [type]="'doughnut'" [data]="myData"[options]="options"></chart>
    </div>
```

...where options look like this:

```
    options = {
            elements: {
                arc :{
                    borderColor: 'rgba(255,255,255,1.0)',
                    borderWidth: 1
                }
            },
            cutoutPercentage: 25,
            animation:{
                animateScale:true
            },                
            responsive: true,
            legend: {
                display: false,             
            }
        }; 
```

Now this produces a chart that is always the same size regardless of the size of its container (too small specifically).  When I look at the resulting DOM there are some quite substantial differences.

Using chart.js directly it seems it can still be used responsively so it seems like maybe this library needs to be updated against the latest version.  I've tried an exhaustive amount of things with the parent container and the styles on the chart element with no change in the results at all.  Directly forcing changes in the canvas size in Chrome's inspector just creates a blurry, stretched image of the chart.

**Comment by jasonburrows** [comment]
Seems like this is specifically related to this:
https://github.com/chartjs/Chart.js/issues/4737

**Comment by emn178** [comment]
v0.4.0 should fix this issue
