### ISSUE TITLE
Cannot find name 'Chart' in ChartComponent

### ISSUE THREAD

**Issue by jjojo** [emn178/angular2-chartjs#3]
Hi, I get this error:

/angular2-chartjs/src/chart.component.ts
(18,22): error TS2304: Cannot find name 'Chart'.

when trying to use the

` @ViewChild(ChartComponent) chartComponent: ChartComponent`

any suggestions on what I'm missing here? or how I can fix it?
code looks like this 
`import { Component, Input, ElementRef, OnInit, OnChanges, SimpleChanges } from '@angular/core';

@Component({
  selector: 'chart',
  template: '</script><canvas></canvas>',
  styles: [':host { display: block; }']
})
export class ChartComponent implements OnInit, OnChanges  {
  chart: any;

  @Input() type: string;
  @Input() data: any;
  @Input() options: any;

  constructor(private elementRef: ElementRef) { }

  ngOnInit() {
    this.chart = new Chart(this.elementRef.nativeElement.querySelector('canvas'), {
      type: this.type,
      data: this.data,
      options: this.options
    });
  }

  ngOnChanges(changes: SimpleChanges) {
    if (this.chart && changes['data']) {
      let currentValue = changes['data'].currentValue;
      ['datasets', 'labels', 'xLabels', 'yLabels'].forEach(property => {
        this.chart.data[property] = currentValue[property];
      })
      this.chart.update();
    }
  }
}`

**Comment by emn178** [comment]
Hi, I can not reproduce your problem. Can you give more detail? Your source code or something. What you posted is angular2-chartjs source code.

**Comment by jjojo** [comment]
I'm sorry, I'm totally new to Ang2 but maybe i forgot to import something but where does the new Chart instance come from?

**Comment by jjojo** [comment]
I solved it, I'm sorry there was no fault in your code. I injected some other views which resulted in some conflicts on the ViewChild. 
I want to take the opportunity to thank you for this lib as well. It is nice and lightweight, keep up the good work!

**Comment by mehs-pge** [comment]
I am getting the same issue.  @jjojo, how did you solve this?  I feel like I am implementing this correctly but must be missing something.  Any advice @emn178 on why this error happens?



[Archive.zip](https://github.com/emn178/angular2-chartjs/files/730957/Archive.zip)
