### ISSUE TITLE
Can't bind to 'type' since it isn't a known property of 'chart'

### ISSUE THREAD

**Issue by luismiguelbravo** [emn178/angular2-chartjs#30]
![image](https://user-images.githubusercontent.com/5140529/33337235-2133a52e-d451-11e7-9fbd-e78b3fe0d3f5.png)

![image](https://user-images.githubusercontent.com/5140529/33337276-3e5a5a6c-d451-11e7-8aba-6879135bcd2e.png)

**Comment by emn178** [comment]
The error means you didn't import module correctly.

**Comment by Q-ten** [comment]
I had this problem. I had to change the order of my imports...

**Comment by emn178** [comment]
@Q-ten what do you mean? Can you give more information?
