### ISSUE TITLE
How to real-time update the max value on yAxis

### ISSUE THREAD

**Issue by luisellenar** [emn178/angular2-chartjs#32]
How can i update real-time the max value of the y-Axis on my chart? 

It's possible?

**Comment by emn178** [comment]
assign new object to options when update?
```JavaScript
options = { ... };
```

**Comment by luisellenar** [comment]
I've tried that but without success, the yAxis don't change max value...

**Comment by luisellenar** [comment]
More detailed problem, i can't call method .update() cause i don't have access to chart element.

**Comment by luisellenar** [comment]
More detailed problem, i can't call method .update() cause i don't have access to chart element.

**Comment by emn178** [comment]
is your version above v0.3.0?
did you create a new object of options and assign?

**Comment by emn178** [comment]
or you want to access chart instance, please refer to https://github.com/emn178/angular2-chartjs#faq

**Comment by luisellenar** [comment]
Yeap, i created an object with options, but i can't change that on runtime, just with static values, i need to set values of my JSON on yAxis everytime this JSON changes.

**Comment by luisellenar** [comment]
When i assign a new object to options nothing happens

**Comment by emn178** [comment]
Is this what you want?
```JavaScript
options = {
    scales: {
        yAxes: [{
            ticks: {
                max: 5 // here you want to update
            }
        }]
    }
};
```

**Comment by stephenheard** [comment]
If you just update the options.scales.yAxes.ticks.max property of an existing options object, it will not trigger the ngOnChanges and rebuild the chart.  I had a similar issue with trying to update the x axis range and came up with this solution:

In my template file:
```
<chart [type]="chartType" [data]="chartData" [options]="chartOptions"></chart>
```

Then, in my component.ts, to make the axis update range work:
```
let options = Object.assign({}, this.chartOptions);
options.scales.xAxes[0].ticks.min = xmin;
options.scales.xAxes[0].ticks.max = xmax;
this.chartOptions = options;
```
