### ISSUE TITLE
How do you update individual charts?

### ISSUE THREAD

**Issue by shyamal890** [emn178/angular2-chartjs#33]
I see https://github.com/emn178/angular2-chartjs/issues/2 where the following is utilized to update chart. 
```
import { ChartComponent } from 'angular2-chartjs';

//...

@ViewChild(ChartComponent) chart: ChartComponent; 

//...

this.chart.chart.update();
```
However, does calling `this.chart.chart.update()` all charts in the component? How do one target a single chart?

@emn178

**Comment by emn178** [comment]
You can use template reference variables.
```HTML
<chart #chart1 ></chart>
```
```TypeScript
@ViewChild('chart1') chart1: ChartComponent; 
```

**Comment by shyamal890** [comment]
@emn178  I created a pull request removing `else` from `ngOnChanges` which auto updates the chart on update to `[data]` attribute.

**Comment by walheredia** [comment]
Please follow this and it will work!

1) Import these ones...

    import { Component, OnInit, ViewChild } from '@angular/core';
    import { BaseChartDirective } from 'ng2-charts';

2) Into the export class (in your ts file) add this...

    @ViewChild(BaseChartDirective) chart: BaseChartDirective;

then, first you should initialize the object that contains the data and label info.
1, 1, 1 is an example, you can use 0 if want...

    public barChartData: any[] = [{
        data: [1,1,1,1,1,1,1],
        label: 'this is an example'
    }];

3) in your ngOnInit method add a setTimeout function, or use the call to the backend by http;

    setTimeout(() => {
        this.chart.chart.data.datasets[0].data = [55, 355, 35, 50, 50, 60, 10]
        this.chart.chart.update()
    }, 2000);

4) in your html file, make sure to add baseChart to the canvas tag

     <div class="chart-wrapper">
      <canvas baseChart class="chart"
      [datasets]="barChartData"
      [labels]="barChartLabels"
      [options]="barChartOptions"
      [legend]="barChartLegend"
      [chartType]="barChartType"
      [colors]="chartColors"
      (chartHover)="chartHovered($event)"
      (chartClick)="chartClicked($event)">
      </canvas>
     </div>

5) just to explore a little more, in the ngOnInit method, you can perform a console.log of (this.chart.chart) and you will find more information about the object...

Hope it helps!
