### ISSUE TITLE
Example not loading

### ISSUE THREAD

**Issue by dgormly** [emn178/angular2-chartjs#34]
Have copied the line chart example into my project but it apprears to not be loading. When I change it to a scatter graph with the example on chartjs website it shows the grid but not the data points. I have not added anything the systemJS as I am new to angular 5. Is this necessary and would this be the problem?

I npm installed systemjs into my program but can't seem to find the config file that it is referencing to. Sorry for the newb questions. I find it weird that it is able to load the graph with no data points though.

**Comment by dgormly** [comment]
Unfortunately I have set my project up through the Cli and those instructions seem to not work :( does anyone have a demo on their github?

**Comment by emn178** [comment]
here is a [sample](https://github.com/emn178/angular2-chartjs-sample)

**Comment by dgormly** [comment]
Thank you! It seems that it is the mat-card that I have surrounded seems to cause issues.

**Comment by dgormly** [comment]
So this seems to have put me back to square one. I have removed the mat-card and it works fine until I swap it to a scatter graph using the example code given on chartjs. Is scatter a supported chart?

**Comment by emn178** [comment]
scatter has different data format. did you change it?

**Comment by dgormly** [comment]
I changed it to the one given in the examples on the website, with options as a seperate variable

**Comment by emn178** [comment]
did you solve your problem?
