### ISSUE TITLE
Event(clickDataset) array was empty

### ISSUE THREAD

**Issue by kohtet02** [emn178/angular2-chartjs#36]
I have updated the angular2-chartjs to 0.5.0 and trying to use the function(event: clickDataset) which was updated recently.

My code is just like following.

```
import { ChartComponent } from 'angular2-chartjs';
@Component({
  selector: 'chartjs-bar',
  template: `
    <chart type="bar" *ngIf="isCompInit" [data]="data" [options]="options" 
    (click)="clickChart($event)"></chart>
  `,
})

...

@ViewChild(ChartComponent) chart: ChartComponent; 
event: any = new EventEmitter;

...

  clickChart(event) {
    this.event = this.chart.clickDataset;
    console.log('Event clicked : ' + this.event);
  }
```
The EventEmitter(clickDataset) from the chart instance doesn't contains the dataset that I clicked on the chart's canvas. 

Could you please let me know the way to get the dataset value when the chart element is clicked.

**Comment by emn178** [comment]
it should be
```HTML
<chart type="bar" *ngIf="isCompInit" [data]="data" [options]="options" 
    (clickDataset)="clickChart($event)"></chart>
```

**Comment by kohtet02** [comment]
Thank you for your quick response. I got the dataset values from clickDataset event.
