### ISSUE TITLE
Bar chart scroll on x-axis 

### ISSUE THREAD

**Issue by Asad-Shah** [emn178/angular2-chartjs#37]
How can i add horizontal scroll on a bar chart ?

**Comment by emn178** [comment]
here is a solution for line chart
https://stackoverflow.com/questions/35854244/how-can-i-create-a-horizontal-scrolling-chart-js-line-chart-with-a-locked-y-axis
bar chart should be similar

**Comment by midhun-qburst** [comment]
This did not work for me. My chart is still getting resized and fitting inside the wrapper.. What could be missing?

**Comment by bhargesh1994** [comment]
yes it marged my x-axis 2 label in 1 data grid and resize it not working.
