### ISSUE TITLE
How to set the size of the chart? (width, height)

### ISSUE THREAD

**Issue by jhertz123** [emn178/angular2-chartjs#4]
Setting the size of the chart seems to do nothing?
<chart [type]="type" [data]="data" width="400" height="400" [options]="options"></chart>

Using style seems to work.
<chart [type]="type" [data]="data" style="width: 835px; height: 300px;" [options]="options"></chart>

What is the correct way?

**Comment by emn178** [comment]
You can think <chart> element is a div, and the chart size will be same. You can use style or CSS to set the size just like a normal html element.
