### ISSUE TITLE
Can we get an upgrade to latest version ?

### ISSUE THREAD

**Issue by macpatel** [emn178/angular2-chartjs#40]
Hi,

I am trying to use some new intersect modes from the example: http://www.chartjs.org/samples/latest/charts/line/basic.html

```
tooltips: {
   mode: 'index',
   intersect: false,
},
```

I tried in chart.js version ^2.3 but it's not working. In ^2.7 it's working fine.

How can we upgrade to latest version ?

**Comment by emn178** [comment]
Yes, you can use 2.7 in your project.
