### ISSUE TITLE
Has anyone figured how to get labels on the outside of a doughnut?

### ISSUE THREAD

**Issue by DanaEpp** [emn178/angular2-chartjs#42]
So I am trying to figure out how to get labels on the outside of a doughnut.

I stumbled across another project from emn178 (https://github.com/emn178/Chart.PieceLabel.js) that seems to do it, but I do not know how to get it to work with angular2-chartjs.

Any ideas?

**Comment by emn178** [comment]
here is an example.
https://github.com/emn178/angular2-chartjs-sample/blob/master/src/app/app.module.ts#L4
change to 
```
import 'chart.piecelabel.js';
```
this should also answer your the other question #39
just change to your custom register plugin

**Comment by DanaEpp** [comment]
Thanks, that worked! For the outer labels at least. Do you have a project for putting labels in the middle of a doughnut?

**Comment by vvsraju04** [comment]
@DanaEpp Were you able to find the solution for putting labels in the middle of the doughnut problem?

**Comment by taxpayer** [comment]
@DanaEpp @vvsraju04 

https://github.com/ciprianciurea/chartjs-plugin-doughnutlabel
