### ISSUE TITLE
 How to change color of hidden legend item instead of strike-through in Chart.js

### ISSUE THREAD

**Issue by ravirajhalli** [emn178/angular2-chartjs#43]
Hi All,

How to change color of hidden legend item instead of strike-through in Chart.js

**Comment by ravirajhalli** [comment]
I am looking for similiar solution provided in following link

https://stackoverflow.com/questions/37949003/how-to-change-color-of-hidden-legend-item-instead-of-strike-through-in-chart-js

**Comment by emn178** [comment]
Looks this issue is about the usage of Chart.js
