### ISSUE TITLE
call Chart.js methods 

### ISSUE THREAD

**Issue by intergleam** [emn178/angular2-chartjs#7]
In the doc you are saying:
>[Chart instance. You can call Chart.js methods via this member.](https://github.com/emn178/angular2-chartjs#chart)

What this supposed to mean? There is no `chartComponent` available

**Comment by emn178** [comment]
Please refer to [this](https://angular.io/docs/ts/latest/cookbook/component-communication.html).
See section `Parent interacts with child via a local variable` and `Parent calls a ViewChild`.

**Comment by mgween** [comment]
Could you please provide an example? I still don't understand how to apply prototype methods.

**Comment by colmben** [comment]
From one of the other issues:

You should use ChartComponent
```

import { ChartComponent } from 'angular2-chartjs';

//...

@ViewChild(ChartComponent) chart: ChartComponent; 

//...

this.chart.chart.update();
```

**Comment by maikelthedev** [comment]
But this doesn't work when you have two charts on the same page.

**Comment by apostnov** [comment]
@maikeldotuk  Sure, in case of multiple components @ViewChildren() should be used. See https://angular.io/api/core/ViewChildren
