### ISSUE TITLE
Does this project work with the Chart.js zoom plugin?

### ISSUE THREAD

**Issue by scotteby** [emn178/angular2-chartjs#8]
I am trying to add zoom functionality to my chart using the chartjs-plugin-zoom project but I haven't been able to get it working yet.

[https://github.com/chartjs/chartjs-plugin-zoom](url)

I added the chartjs-plugin-zoom and the hammerjs dependency to my project. I have the zoom property added to my chart config as well.

Just curious if anyone else has got this plugin working?

**Comment by emn178** [comment]
It works for me. Did you import chartjs-plugin-zoom? something like
```TypeScript
import 'chartjs-plugin-zoom'
```
or
```TypeScript
require('chartjs-plugin-zoom');
```

**Comment by TheSegfault** [comment]
Not working for me either, the plugin is supposed to be injected by himself through npm install no ?

I tested your imports @emn178 it doesn't change anything.

@scotteby did u find something ?

**Comment by mac10046** [comment]
Can anyone of you give a demo - repo code ?? for better explanation.

**Comment by emn178** [comment]
@mac10046 https://github.com/emn178/angular2-chartjs-sample

**Comment by sridhark158** [comment]
@TheSegfault  Thank you so much it's working fine to me :)
