### ISSUE TITLE
Use with webpack

### ISSUE THREAD

**Issue by beckmx** [emn178/angular2-chartjs#9]
Hello, I was trying to implement it with webpack but I am having some problems, when I try to use start up the app it generates an error with angular 2.0.2

**Comment by emn178** [comment]
what error? how do you use?

**Comment by beckmx** [comment]
First I use npm to install the angular2-chartjs, then in my  webpack vendor file which is:

`var isDevBuild = process.argv.indexOf('--env.prod') < 0;
var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var merge = require('webpack-merge');
var extractCSS = new ExtractTextPlugin('vendor.css');
var CopyWebpackPlugin = require('copy-webpack-plugin');



console.log(__dirname);
var sharedConfig = {
    resolve: { extensions: ['', '.js'] },
    module: {
        loaders: [
            { test: /\.json$/, loader: require.resolve('json-loader') },
            { test: /\.(png|woff|woff2|eot|ttf|svg)(\?|$)/, loader: 'url-loader?limit=100000' },
        ]
    },
    entry: {
        vendor: [
            '@angular/common',
            '@angular/compiler',
            '@angular/core',
            '@angular/http',
            '@angular/platform-browser',
            '@angular/platform-browser-dynamic',
            '@angular/router',
            '@angular/platform-server',
            'angular2-universal',
            'angular2-universal-polyfills',
            'bootstrap',
            'bootstrap/dist/css/bootstrap.css',
            'es6-shim',
            'es6-promise',
            'event-source-polyfill',
            'jquery',
            'zone.js',
            'chart.js',
            'angular2-chartjs'
        ]
    },
    output: {
        publicPath: '/dist/',
        filename: '[name].js',
        library: '[name]_[hash]'
    },
    plugins: [
        new CopyWebpackPlugin([{ from: path.join(__dirname, './node_modules/chart.js/dist/Chart.js'), to: path.join(__dirname, './wwwroot/vendor/Chart.js') }]),
        new CopyWebpackPlugin([{ from: path.join(__dirname, './node_modules/d3/d3.min.js'), to: path.join(__dirname, './wwwroot/vendor/d3.js') }]),
        new CopyWebpackPlugin([{ from: path.join(__dirname, './node_modules/nvd3/build/nv.d3.min.js'), to: path.join(__dirname, './wwwroot/vendor/nv.d3.min.js') }]),
        new CopyWebpackPlugin([{ from: path.join(__dirname, './node_modules/nvd3/build/nv.d3.min.css'), to: path.join(__dirname, './wwwroot/vendor/nv.d3.min.css') }]),
        new webpack.ProvidePlugin({ $: 'jquery', jQuery: 'jquery' }), // Maps these identifiers to the jQuery package (because Bootstrap expects it to be a global variable)
        new webpack.ContextReplacementPlugin(/\@angular\b.*\b(bundles|linker)/, path.join(__dirname, './ClientApp')), // Workaround for https://github.com/angular/angular/issues/11580
        new webpack.IgnorePlugin(/^vertx$/), // Workaround for https://github.com/stefanpenner/es6-promise/issues/100
        new webpack.NormalModuleReplacementPlugin(/\/iconv-loader$/, require.resolve('node-noop')), // Workaround for https://github.com/andris9/encoding/issues/16
    ]
};

var clientBundleConfig = merge(sharedConfig, {
    output: { path: path.join(__dirname, 'wwwroot', 'dist') },
    module: {
        loaders: [
            { test: /\.css(\?|$)/, loader: extractCSS.extract(['css-loader']) }
        ]
    },
    plugins: [
        extractCSS,
        new webpack.DllPlugin({
            path: path.join(__dirname, 'wwwroot', 'dist', '[name]-manifest.json'),
            name: '[name]_[hash]'
        })
    ].concat(isDevBuild ? [] : [
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.optimize.UglifyJsPlugin({ compress: { warnings: false } })
    ])
});

var serverBundleConfig = merge(sharedConfig, {
    target: 'node',
    resolve: { packageMains: ['main'] },
    output: {
        path: path.join(__dirname, 'ClientApp', 'dist'),
        libraryTarget: 'commonjs2',
    },
    module: {
        loaders: [{ test: /\.css(\?|$)/, loader: 'to-string-loader!css-loader' }]
    },
    entry: { vendor: ['aspnet-prerendering'] },
    plugins: [
        new webpack.DllPlugin({
            path: path.join(__dirname, 'ClientApp', 'dist', '[name]-manifest.json'),
            name: '[name]_[hash]'
        })
    ]
});

module.exports = [clientBundleConfig, serverBundleConfig];`

The webpack output correctly bundles but when I try to load the site it won't load and says window is not defined. If I take out the dependencies on the config file and put them on the main layout index, it will load correctly, I wonder why?

**Comment by emn178** [comment]
Hi,

Your config looks complicated. I can't know where problem is.
This is my workable config https://github.com/emn178/angular2-chartjs/blob/master/webpack.config.js
I put dependencies in app.ts
Or you can try angular-cli to build project. It is easier.
